# Generated by Django 2.2.2 on 2019-06-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('discount', models.FloatField()),
            ],
        ),
    ]
